# Generated by Django 4.1.5 on 2023-01-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del servicio ó producto', max_length=60)),
                ('descripcion', models.CharField(help_text='Descripcion del servicio ó producto', max_length=100)),
                ('tipo', models.CharField(choices=[('Servicio', 'Servicio'), ('Producto', 'Producto')], max_length=10)),
                ('imagen', models.ImageField(help_text='foto del servicio ó producto', upload_to='servicios')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Quien añade el producto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'servicio ó producto',
                'verbose_name_plural': 'servicios ó productos',
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo del post', max_length=60)),
                ('contenido', models.CharField(help_text='Contenido del post', max_length=100)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del post', null=True, upload_to='blog')),
                ('link', models.URLField(blank=True, help_text='Link de una publicacion externa sobre el post', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Quien publica este post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ManyToManyField(help_text='Categoria del post', to='AndresMogollonApp.categorias')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
