# Generated by Django 4.1.5 on 2023-01-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo de la educacion', max_length=250)),
                ('institucion', models.CharField(help_text='Institucion que otorga la educacion', max_length=250)),
                ('descripcion', models.CharField(help_text='Descripcion de la educacion', max_length=250)),
                ('inicio', models.DateField(help_text='Fecha de inicio de la educacion')),
                ('fin', models.DateField(help_text='Fecha de finalizacion de la educacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'educacion',
                'verbose_name_plural': 'educaciones',
            },
        ),
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(help_text='Puesto de la experiencia', max_length=250)),
                ('empresa', models.CharField(help_text='Empresa que otorga la experiencia', max_length=250)),
                ('inicio', models.DateField(help_text='Fecha de inicio de la experiencia')),
                ('fin', models.DateField(help_text='Fecha de finalizacion de la experiencia')),
                ('descripcion', models.CharField(help_text='Descripcion de la experiencia', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'experiencia',
                'verbose_name_plural': 'experiencias',
            },
        ),
    ]
