# Generated by Django 4.1.5 on 2023-01-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0004_educacion_experiencia_delete_educacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion_experiencia',
            name='fin',
            field=models.DateField(blank=True, help_text='Fecha de finalizacion de la educacion ó experiencia', null=True),
        ),
    ]
