# Generated by Django 4.1.5 on 2023-01-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0005_alter_educacion_experiencia_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='educacion_experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Educacion', 'Educacion'), ('Experiencia', 'Experiencia')], max_length=11)),
                ('nombre', models.CharField(help_text='Nombre de la educacion ó experiencia', max_length=250)),
                ('institucion', models.CharField(help_text='Institucion que otorga la educacion ó experiencia', max_length=250)),
                ('descripcion', models.CharField(help_text='Descripcion de la educacion ó experiencia', max_length=250)),
                ('anio_inicio', models.IntegerField(help_text='Año de inicio de la educacion ó experiencia')),
                ('anio_fin', models.IntegerField(blank=True, help_text='Año de finalizacion de la educacion ó experiencia', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'educacion ó experiencia',
                'verbose_name_plural': 'educaciones ó experiencias',
            },
        ),
        migrations.DeleteModel(
            name='educacion_experiencia',
        ),
    ]
