# Generated by Django 4.1.5 on 2023-01-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0006_educacion_experiencias_delete_educacion_experiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educacion_experiencias',
            old_name='anio_fin',
            new_name='fin',
        ),
        migrations.RenameField(
            model_name='educacion_experiencias',
            old_name='anio_inicio',
            new_name='inicio',
        ),
    ]
