# Generated by Django 4.1.5 on 2023-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0009_alter_educacion_experiencias_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion_experiencias',
            name='fin',
            field=models.IntegerField(blank=True, help_text='Año de finalizacion de la educacion ó experiencia', null=True),
        ),
    ]
