# Generated by Django 4.1.5 on 2023-01-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0012_proyectos_delete_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='git',
            field=models.URLField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='host',
            field=models.URLField(blank=True, max_length=230, null=True),
        ),
    ]
