# Generated by Django 4.1.5 on 2023-01-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0013_alter_proyectos_git_alter_proyectos_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='categorias',
        ),
        migrations.DeleteModel(
            name='servicio',
        ),
    ]
