# Generated by Django 4.1.5 on 2023-01-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0014_remove_servicio_autor_remove_post_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(help_text='Contenido del post', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='Titulo del post', max_length=160),
        ),
    ]
