# Generated by Django 4.1.5 on 2023-01-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0016_documentos_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
