# Generated by Django 4.1.5 on 2023-01-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0017_alter_documentos_nombre_alter_fotos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
