# Generated by Django 4.1.5 on 2023-01-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0018_alter_fotos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='foto')),
                ('tipo', models.CharField(choices=[('Perfil', 'Perfil'), ('Portada', 'Portada')], max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
        migrations.DeleteModel(
            name='fotos',
        ),
    ]
