# Generated by Django 4.1.5 on 2023-01-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0019_foto_delete_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='nombre',
        ),
    ]
