# Generated by Django 4.1.5 on 2023-01-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0020_remove_documentos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='tipo',
            field=models.CharField(choices=[('Perfil', 'Perfil'), ('Portada', 'Portada')], max_length=7, unique=True),
        ),
    ]
