# Generated by Django 4.1.5 on 2023-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndresMogollonApp', '0022_proyectos_frameworks_proyectos_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion_experiencias',
            name='fin',
            field=models.CharField(default=1, help_text='Año de fin de la educacion ó experiencia', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educacion_experiencias',
            name='inicio',
            field=models.CharField(help_text='Año de inicio de la educacion ó experiencia', max_length=12),
        ),
    ]
